In [1]:
import numpy as np

In [14]:
om = np.exp(1j*2*np.pi/3)

phi_2 = np.array([1, om, om**2,
                  -1, -om, om**2,
                 -1, om, -om**2,
                 1, -om, -om**2])

phi_3 = np.array([1, om**2, om,
                  -1, -om**2, om,
                 -1, om**2, -om,
                 1, -om**2, -om])

In [ ]:
np.isclose(psi_2, np.conj(psi_3))

In [5]:
np.round(psi_2 - psi_3, decimals=3)

array([ 0.   ,  1.732, -1.732,  0.   , -1.732, -1.732,  0.   ,  1.732,
        1.732,  0.   , -1.732,  1.732])

In [9]:
alpha = np.exp(-1j*2*np.pi/3)
def H(qx, qy, qz):
    arr = np.array([[qx*qy*qz, qx**2 + alpha*qy**2+alpha**2*qz**2],
                    [qx**2+alpha**2*qy**2+alpha**2*qz**2, -qx*qy*qz]])
    return arr

In [22]:
H(0, 0, 1).round(2)

e, v = np.linalg.eig(H(0, 0, 1))

In [24]:
v

array([[-0.70710678+0.j        ,  0.70710678+0.j        ],
       [-0.35355339+0.61237244j, -0.35355339+0.61237244j]])

In [16]:
phi_2

array([ 1. +0.j       , -0.5+0.8660254j, -0.5-0.8660254j, -1. +0.j       ,
        0.5-0.8660254j, -0.5-0.8660254j, -1. +0.j       , -0.5+0.8660254j,
        0.5+0.8660254j,  1. +0.j       ,  0.5-0.8660254j,  0.5+0.8660254j])